<?php

namespace app\models;

//use app\models\Titles;

class Controller extends \yii\web\Controller
{

    public function generateTitle()
    {
//        $this->view->title = 'Web Shop';
//        $this->view->title = __METHOD__;
        if($this->module->id === 'admin') {
            return 'Admin panel';
        } else {
            $title = Titles::findOne(['title_id' => $this->action->uniqueId]);
            return ($title) ? $title->pattern : '';
        }
//        return $this->action->uniqueId;
    }

    public function beforeAction($action)
    {
        $this->view->title = $this->generateTitle();
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}