<?php

namespace app\models;

use yii\base\Model;

/*
 * This is the model class for products display filters
 * @propertys string $... generated by DynamicModel
 */

class Filters extends Model
{

    /**
     * @return array the brands for filter form.
     */
    public static function getBrandsForFilter($filterinfo)
    {
        $brands = [];
        foreach ($filterinfo as $fi) {
            $brands['brand' . $fi['brand_id']] = $fi['brand_name'];
        }
        asort($brands);
        return $brands;
    }

}
